
import React from "react";
import { AlertTriangle } from "lucide-react";

const LegalDisclaimer: React.FC = () => {
  return (
    <section id="legal" className="py-12 px-4 bg-cyberpunk-darker-bg/80">
      <div className="container mx-auto max-w-7xl">
        <div className="max-w-4xl mx-auto bg-black/30 border border-white/10 rounded-lg p-6">
          <div className="flex items-start gap-4">
            <AlertTriangle size={24} className="text-cyberpunk-neon-pink flex-shrink-0 mt-1" />
            
            <div>
              <h3 className="text-xl font-bold mb-4">Legal Disclaimer</h3>
              
              <div className="space-y-4 text-sm text-gray-300">
                <p>
                  GODMODE GPT is provided "as is" without warranties of any kind, either express or implied. The creators and operators of GODMODE GPT make no representations or warranties of any kind concerning the safety, suitability, accuracy, or applicability of the content, suggestions, or outputs generated by this AI tool.
                </p>
                
                <p>
                  Users are solely responsible for verifying any information or content produced by GODMODE GPT before relying on it. The tool should not be used for making critical decisions in areas including but not limited to legal, medical, financial, or safety matters without appropriate human expert consultation.
                </p>
                
                <p>
                  By using GODMODE GPT, you acknowledge that AI systems have limitations and may produce inaccurate, misleading, or contextually inappropriate content despite best efforts at creating reliable systems. You agree to use this tool at your own risk and exercise appropriate judgment when acting on outputs from this system.
                </p>
                
                <p>
                  The creators and operators of GODMODE GPT shall not be liable for any direct, indirect, incidental, special, consequential, or exemplary damages resulting from your use of the service or for any loss of data, revenue, profits, or reputation that may result from using this tool.
                </p>
                
                <p>
                  This tool is not designed to collect or store sensitive personal information. Users should refrain from sharing confidential or sensitive personal data with the system.
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
};

export default LegalDisclaimer;
